#!/bin/bash
curl -X POST localhost:5000/api/todos -d "{\"name\": \"Tarefa 1\"}" -v
curl -X POST localhost:5000/api/todos -d "{\"name\": \"Tarefa 2\"}" -v
echo "Dados Salvos"

curl localhost:5000/api/todois -v 
